export {ReactComponent as Sun } from './sun.svg';
export {ReactComponent as DegreesCelCius} from './degrees-celcius.svg';
export {ReactComponent as RainDrop} from './raindrop.svg';
export {ReactComponent as CloudWind} from './cloud-wind.svg';
export {ReactComponent as Marker} from './marker.svg';
export {ReactComponent as CloudFogSun} from './cloud-fog-sun.svg';
export {ReactComponent as Cloud} from './cloud.svg';
export {ReactComponent as Clouds} from './clouds.svg';
export {ReactComponent as CloudRain} from './cloud-rain.svg';
export {ReactComponent as Rain} from './rain.svg';
export {ReactComponent as CloudLightning} from './cloud-lightning.svg';
export {ReactComponent as CloudSnow} from './cloud-snow.svg';
export {ReactComponent as Fog} from './fog.svg';